### ISSUE TITLE
The most awkward issue I've ever filed

### ISSUE THREAD

**Issue by DamieFC** [Smart6502/Smart6502#1]
Ok, so, I know it's weird to open an issue on a profile readme, but https://github.com/Smart6502/charon is nonexistent. I get a 404 page.

**Comment by Smart6502** [comment]
I have deleted the repository, I haven't updated the README so when you click the link, you get a 404.
I will update the README. Thanks haha.

**Comment by DamieFC** [comment]
No problem!
